/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux DESKTOP-T42BJ1H 5.10.16.3-microsoft-standard-WSL2 x86_64"
#define LGL_COMPILED "Fri Aug 13 11:06:44 CEST 2021"
#define LGL_RELEASED "Thu May 17 11:57:41 CEST 2018"
#define LGL_VERSION "bcj"
#define LGL_ID "78ebb8672540bde0a335aea946bbf32515157d5a"
